Repository taiki-e/cargo-hack, pull requests merged in 2023-09, with the labels that each got.

#198 Support ..= for --version-range
  README.md
  src/cli.rs
  src/rustup.rs
  tests/auxiliary/mod.rs
  tests/long-help.txt
  tests/short-help.txt
  tests/test.rs
Labels: A-version-range

#207 Reject inclusive range without end expression
  src/version.rs
  tests/test.rs
Labels: A-version

#213 feat: Support mixed MSRV in --version-range
  src/main.rs
  src/rustup.rs
  tests/test.rs
Labels: A-version

#214 Add --log-group option to opt-out/force-enable log grouping
  README.md
  src/cli.rs
  src/context.rs
  src/main.rs
  tests/long-help.txt
  tests/short-help.txt
  tests/test.rs
Labels: A-diagnostics

#219 Group rustup output on GitHub Actions
  .github/workflows/ci.yml
  src/main.rs
  src/rustup.rs
Labels: A-diagnostics
